Revert "cargo update"
This reverts commit 112c702f2246758e217f70604c3ed9e088d5997c.

Something is causing:
error: attempted to run an executor while another executor is already running